### ISSUE TITLE
想请问一下这个是源码吗？怎么打包呀？

### ISSUE THREAD

**Issue by darrenliuwei** [aaamoon/react1s#1]
公司内网连不上Google插件商店，我想打包到本地，然后再传到内网。

是不是还缺少`manifest.json`文件呀？

**Comment by aaamoon** [comment]
对的，这个是源码，可以把代码拉到本地，然后 yarn   -->  yran zip 就能生成zip包了

**Comment by aaamoon** [comment]
这个是用plasmo写的，生成的zip包里面有manifest.json

**Comment by aaamoon** [comment]
我上传了zip包，在build目录下，你可以下载到本地然后自行到浏览器拓展

**Comment by darrenliuwei** [comment]
> 我上传了zip包，在build目录下，你可以下载到本地然后自行上传到浏览器拓展

好的，感谢~
