### ISSUE TITLE
目前使用情况下的两个痛点

### ISSUE THREAD

**Issue by huangdafei645** [aaamoon/react1s#6]
![image](https://github.com/aaamoon/react1s/assets/102475833/212361ac-5e02-4b79-ab77-bdde96db30ec)
当我每次点击的时候， 都会弹出这样一个提示框， 我点击yes之后就会自动打开vscode， 现在对我自己来说有两个痛点：
1. 每次点击后， 编辑器会新打开一个状态页（win的话，鼠标移到状态栏对应得编辑器图标上出现多个页面）， 这样一个一个关闭实在是太烦琐了
2. 每次点击后会出现一个类似上图的confirm选项， 能解决的话， 我自己应该是会长期使用， 并会在小组推荐

**Comment by Amor128** [comment]
![image](https://github.com/aaamoon/react1s/assets/71883627/a7bb2354-a921-40e6-a96b-72f07949b31d)
问题同上，如果上一个对话框长时间不点击，还会弹出第二个对话框

**Comment by aaamoon** [comment]
好的，这两天我找一台window的电脑看看这个问题哈

**Comment by aaamoon** [comment]
@huangdafei645 @Amor128 这个问题看起来是 Windows 系统的 VS Code 的 URI 安全策略限制，可以试下这个方法看行不行：
https://github.com/microsoft/vscode/issues/95670#issuecomment-1112338960
