### ISSUE TITLE
wsl2 开发环境用不了

### ISSUE THREAD

**Issue by xiaorong61** [aaamoon/react1s#7]
vscode 使用 wsl 扩展链接 wsl2，并在 vscode 启动项目，在网页上选择组件弹窗点击确定时显示：
![image](https://github.com/aaamoon/react1s/assets/5251387/d36f2a6d-4d8e-42b4-8b59-5ed7998423d8)

**Comment by aaamoon** [comment]
对于普通的 Windows 和 Mac 系统的跳转路径是这样的：vscode://file/${fileName}:${lineNumber}:${columnNumber}

更新了一个新版本支持了自定义路径，我不太清楚 wsl2 的路径前缀是怎样的，你可以多试试，你可以试下设置成比如：
vscode://vscode-remote/wsl+Ubuntu/home/${fileName}:${lineNumber}:${columnNumber}

<img width="349" alt="image" src="https://github.com/aaamoon/react1s/assets/25700476/4dbf0003-e734-4db1-81f5-9f668678bbe3">

**Comment by xiaorong61** [comment]
> 对于普通的 Windows 和 Mac 系统的跳转路径是这样的：vscode://file/${fileName}:${lineNumber}:${columnNumber}
> 
> 更新了一个新版本支持了自定义路径，我不太清楚 wsl2 的路径前缀是怎样的，你可以多试试，你可以试下设置成比如： vscode://vscode-remote/wsl+Ubuntu/home/${fileName}:${lineNumber}:${columnNumber}
> 
> <img alt="image" width="349" src="https://user-images.githubusercontent.com/25700476/254450781-4dbf0003-e734-4db1-81f5-9f668678bbe3.png">

![image](https://github.com/aaamoon/react1s/assets/5251387/0ee688c3-4697-4051-9ed7-049964968337)
我觉得需要括号扩一下

**Comment by aaamoon** [comment]
已修复，Chrome插件发了个新版本，审核中，应该下午就好了

**Comment by xiaorong61** [comment]
谢谢，因商店没更新，刚刚我用 zip 加载了 扩展，Arch Linux 用
···
vscode://vscode-remote/wsl+Arch/${fileName}:${lineNumber}:${columnNumber}
···
可正常工作了，需去掉路径的 home。
