### ISSUE TITLE
控制台有打印信息，但是无法打开vscode

### ISSUE THREAD

**Issue by dtless** [aaamoon/react1s#9]
vscode和Chrome都是最新版本，控制台有输出，能帮忙看下吗？

<img width="1532" alt="image" src="https://github.com/aaamoon/react1s/assets/16819527/83fd47e7-20f5-44e5-94ae-6cb39969124f">

**Comment by aaamoon** [comment]
你用的vscode是insider版本(绿色icon的图标)吗，如果是的话，需要选择
<img width="399" alt="截屏2023-11-02 下午4 41 54" src="https://github.com/aaamoon/react1s/assets/25700476/b2b9bd89-4e70-4337-830e-77f7cc6eb282">

**Comment by mingxin-yang** [comment]
有同样问题，选第一个会打开vscode，但跳转不到相应位置，选第二个不会打开vscode，一开始好的，今天不行了，不知道怎么回事 @aaamoon

**Comment by rr210** [comment]
选择哪个都打不开了

**Comment by rr210** [comment]
临时解决方法：https://github.com/infi-pc/locatorjs/issues/127

**Comment by aaamoon** [comment]
> 临时解决方法：[infi-pc/locatorjs#127](https://github.com/infi-pc/locatorjs/issues/127)

感谢

**Comment by aaamoon** [comment]
这是 VS Code 在最新版本 1.84 更新导致的问题，如果大家遇到在 VS Code 中有问题打不开的情况， 可以在插件的设置面板选择自定义路径
<img width="359" alt="image" src="https://github.com/aaamoon/react1s/assets/25700476/89f4e971-caee-4a9e-868c-249afd4236fb">，
然后输入内容 vscode://file${fileName}:${lineNumber}:${columnNumber}
然后点击更新即可

**Comment by liuyib** [comment]
> 这是 VS Code 在最新版本 1.84 更新导致的问题，如果大家遇到在 VS Code 中有问题打不开的情况， 可以在插件的设置面板选择自定义路径 <img alt="image" width="359" src="https://user-images.githubusercontent.com/25700476/282393673-89f4e971-caee-4a9e-868c-249afd4236fb.png">， 然后输入内容 vscode://file${fileName}:${lineNumber}:${columnNumber} 然后点击更新即可

这个设置截图放到 README 里吧，翻到这个 issue 才知道咋设置自定义路径，还以为是 vscode 的设置，哈哈

**Comment by aaamoon** [comment]
> > 这是 VS Code 在最新版本 1.84 更新导致的问题，如果大家遇到在 VS Code 中有问题打不开的情况， 可以在插件的设置面板选择自定义路径 <img alt="image" width="359" src="https://user-images.githubusercontent.com/25700476/282393673-89f4e971-caee-4a9e-868c-249afd4236fb.png">， 然后输入内容 vscode://file${fileName}:${lineNumber}:${columnNumber} 然后点击更新即可
> 
> 翻到这个 issue 才知道咋设置自定义路径，还以为是 vscode 的设置，哈哈
> 
> ![image](https://user-images.githubusercontent.com/38221479/282997857-76b5ab26-bc74-45dd-a243-8fe6ebe9c2d2.png)
> 
> 上图这个“编辑器设置”是不是有些歧义呢？我理解的是 vscode 设置，其实是 react1s 插件的配置面板

哈哈，确实有点歧义，我改一下
